const form = {
  formId: "edit-contact-organisation",
  formField: {
    nom: {
      name: "nom",
      label: "Nom",
      type: "text",
      errorMsg: "Nom est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "Nom est invalide.",
      placeholder: "Veuillez saisir le Nom",
    },
    prenom: {
      name: "prenom",
      label: "Prénom",
      type: "text",
      errorMsg: "prénom est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "prénom est invalide.",
      placeholder: "Veuillez saisir le prénom",
    },
    e_mail: {
      name: "e_mail",
      label: "E-mail",
      type: "email",
      errorMsg: "E-mail est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "E-mail est invalide.",
      placeholder: "Veuillez saisir le E-mail",
    },
    entreprise: {
      name: "entreprise",
      label: "Entreprise",
      type: "text",
      errorMsg: "Entreprise est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "Entreprise est invalide.",
      placeholder: "Veuillez saisir l'Entreprise",
    },
    adresse: {
      name: "adresse",
      label: "Adresse",
      type: "text",
      errorMsg: "Adresse est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "Adresse est invalide.",
      placeholder: "Veuillez saisir l'Adresse",
    },
    code_postal: {
      name: "code_postal",
      label: "Code Postal",
      type: "number",
      errorMsg: "Code Postal est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "Code Postal est invalide.",
      placeholder: "Veuillez saisir le Code Postal",
    },
    ville: {
      name: "ville",
      label: "Ville",
      type: "text",
      errorMsg: "Ville est obligatoire.",
      minValue: "Au moin 2 charactère.",
      invalidMsg: "Ville est invalide.",
      placeholder: "Veuillez saisir le Ville",
    },

    statut: {
      name: "statut",
      label: "Statut",
      errorMsg: "Statut est obligatoire.",
      invalidMsg: "Statut est invalide.",
      placeholder: "Veuillez choisir le Statut",
    },
  },
};
export default form;
